
export const dominoImageMappings = {
    d1: require("../assets/images/d1.png"),
    d2: require("../assets/images/d2.png"),
    d3: require("../assets/images/d3.png"),
    d4: require("../assets/images/d4.png"),
    d5: require("../assets/images/d5.png"),
    d6: require("../assets/images/d6.png"),
    d7: require("../assets/images/d7.png"),
    d8: require("../assets/images/d8.png"),
    d9: require("../assets/images/d9.png"),
    d10: require("../assets/images/d10.png"),
    d11: require("../assets/images/d11.png"),
    d12: require("../assets/images/d12.png"),
    d13: require("../assets/images/d13.png"),
    d14: require("../assets/images/d14.png"),
    d15: require("../assets/images/d15.png"),
    d16: require("../assets/images/d16.png"),
    d17: require("../assets/images/d17.png"),
    d18: require("../assets/images/d18.png"),
    d19: require("../assets/images/d19.png"),
    d20: require("../assets/images/d20.png"),
    d21: require("../assets/images/d21.png"),
    d22: require("../assets/images/d22.png"),
    d23: require("../assets/images/d23.png"),
    d24: require("../assets/images/d24.png"),
    d25: require("../assets/images/d25.png"),
  };